### ISSUE TITLE
Matching causes NPE

### ISSUE THREAD

**Issue by vertti** [lkoskela/maven-build-utils#3]
In the end of outputting the timing table I randomly get NPE. I'm currently unable to consistently reproduce this though.

[ERROR] Internal error: java.lang.RuntimeException: java.lang.NullPointerException -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: java.lang.NullPointerException
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:168)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
    at com.lassekoskela.maven.buildevents.FieldMatcher.matches(FieldMatcher.java:26)
    at org.hamcrest.core.AllOf.matches(AllOf.java:24)
    at ch.lambdaj.Lambda.select(Lambda.java:302)
    at ch.lambdaj.Lambda.select(Lambda.java:315)
    at ch.lambdaj.collection.LambdaIterable.doRetain(LambdaIterable.java:101)
    at ch.lambdaj.collection.LambdaList.retain(LambdaList.java:33)
    at com.lassekoskela.maven.buildevents.BuildEventLogReport.filter(BuildEventLogReport.java:105)
    at com.lassekoskela.maven.buildevents.BuildEventLogReport.totalDurationOfPhase(BuildEventLogReport.java:97)
    at com.lassekoskela.maven.buildevents.BuildEventLogReport.reportBuildStep(BuildEventLogReport.java:50)
    at com.lassekoskela.maven.buildevents.BuildEventLogReport.reportBuildSteps(BuildEventLogReport.java:39)
    at com.lassekoskela.maven.buildevents.BuildEventLogReport.report(BuildEventLogReport.java:30)
    at com.lassekoskela.maven.buildevents.BuildEventLog.report(BuildEventLog.java:31)
    at com.lassekoskela.maven.buildevents.BuildEventListener.sessionEnded(BuildEventListener.java:16)
    at com.lassekoskela.maven.buildevents.ExecutionListenerChain.sessionEnded(ExecutionListenerChain.java:39)
    at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:64)
    at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:170)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    ... 11 more
Caused by: java.lang.NullPointerException
    at com.lassekoskela.maven.buildevents.FieldMatcher.matches(FieldMatcher.java:22)
    ... 29 more

**Comment by vertti** [comment]
This was only in 1.3, commit 83dcd1c02c61cd3a35a42550e470bb7002d54b10 fixes this in 1.4-snapshot. I think it was cause by `android-maven-plugin`.
